apps/tasks/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.TaskListView.as_view(),
        name='task-list'
    ),
    url(
        regex=r'^create/$',
        view=views.TaskCreateView.as_view(),
        name='task-create'
    ),
    url(
        regex=r'^available/$',
        view=views.AvailableTaskListView.as_view(),
        name='available-task-list'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/$',
        view=views.TaskDetailView.as_view(),
        name='task-detail'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/apply/$',
        view=views.TaskApplyView.as_view(),
        name='apply'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/rate/$',
        view=views.TaskRatingView.as_view(),
        name='rate'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/status/update/$',
        view=views.TaskStatusUpdateView.as_view(),
        name='status-update'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/tasker/accept/$',
        view=views.AcceptTaskerView.as_view(),
        name='accept-tasker'
    ),
]

apps/users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^profile/(?P<pk>\d+)/$',
        view=views.ProfileView.as_view(),
        name='profile'
    ),
]

lorencecrowdboticscom_lore_634/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url('', include('home.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/v1/', include('home.api.v1.urls')),
    url(r'^admin/', admin.site.urls),
]

tasker/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url('', include('home.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/v1/', include('home.api.v1.urls')),
    url(r'^admin/', admin.site.urls),

    url(
        r'^tasks/',
        include(('apps.tasks.urls', 'app.tasks'), namespace='tasks')
    ),
    url(
        r'^users/',
        include(('apps.users.urls', 'app.users'), namespace='users')
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load i18n staticfiles bootstrap4 %}
<html>
    <head>
        {% bootstrap_css %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        {% block header_css %}{% endblock header_css %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% if user.is_anonymous %}{% url 'home' %}{% else %}{% url 'dashboard' %}{% endif %}">Tasker</a>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                    {% if not user.is_anonymous %}
                        {% if user.type == user.TYPE_TASKER %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'tasks:available-task-list' %}"><i class="fas fa-search"></i> Search </a>
                            </li>
                        {% endif %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tasks:task-list' %}"><i class="fas fa-list-alt"></i> Tasks</a>
                        </li>

                        {% if user.type == user.TYPE_CUSTOMER %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'tasks:task-create' %}"><i class="fas fa-plus-square"></i> Add </a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
                {% if user.is_anonymous %}
                    <span class="navbar-text">
                        <a href="{% url 'account_signup' %}" class="nav-link">Sign Up</a>
                    </span>
                    <span class="navbar-text">
                        <a href="{% url 'account_login' %}" class="nav-link">Log In</a>
                    </span>
                {% else %}
                    <span class="navbar-text">
                        <a href="{% url 'users:profile' user.id %}" class="nav-link"><i class="fas fa-user"></i> Profile</a>
                    </span>
                    <span class="navbar-text">
                        <a href="{% url 'account_logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i> Logout</a>
                    </span>
                {% endif %}
            </div>
        </nav>
        <div class="container">
        {% block content %}{% endblock content %}
    </div>
</body>
{% bootstrap_javascript jquery='full' %}
{% block footer_js %}{% endblock footer_js %}
</html>