apps/tasks/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.TaskListView.as_view(),
        name='task-list'
    ),
    url(
        regex=r'^create/$',
        view=views.TaskCreateView.as_view(),
        name='task-create'
    ),
    url(
        regex=r'^available/$',
        view=views.AvailableTaskListView.as_view(),
        name='available-task-list'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/$',
        view=views.TaskDetailView.as_view(),
        name='task-detail'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/apply/$',
        view=views.TaskApplyView.as_view(),
        name='apply'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/rate/$',
        view=views.TaskRatingView.as_view(),
        name='rate'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/status/update/$',
        view=views.TaskStatusUpdateView.as_view(),
        name='status-update'
    ),
    url(
        regex=r'^(?P<pk>[-:\w]+)/tasker/accept/$',
        view=views.AcceptTaskerView.as_view(),
        name='accept-tasker'
    ),
]

apps/users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^profile/(?P<pk>\d+)/$',
        view=views.ProfileView.as_view(),
        name='profile'
    ),
]

lorencecrowdboticscom_lore_634/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url('', include('home.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/v1/', include('home.api.v1.urls')),
    url(r'^admin/', admin.site.urls),
]

tasker/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url('', include('home.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/v1/', include('home.api.v1.urls')),
    url(r'^admin/', admin.site.urls),

    url(
        r'^tasks/',
        include(('apps.tasks.urls', 'app.tasks'), namespace='tasks')
    ),
    url(
        r'^users/',
        include(('apps.users.urls', 'app.users'), namespace='users')
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/tasks/models.py
import uuid

from django.db import models
from django.utils.translation import ugettext_lazy as _

from apps.core.models import OPTIONAL, TimeStampedModel
from apps.core.utils import get_images_upload_path


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=50)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name


class Task(TimeStampedModel):
    STATUS_PENDING = 1
    STATUS_ACCEPTED = 2
    STATUS_IN_PROGRESS = 3
    STATUS_DONE = 4
    STATUS_CHOICES = (
        (STATUS_PENDING, 'Pending'),
        (STATUS_ACCEPTED, 'Accepted'),
        (STATUS_IN_PROGRESS, 'In Progress'),
        (STATUS_DONE, 'Done'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category = models.ForeignKey(
        'tasks.Category',
        verbose_name=_('Category'),
        related_name='tasks',
        on_delete=models.CASCADE
    )
    customer = models.ForeignKey(
        'users.User',
        verbose_name=_('Customer'),
        related_name='tasks',
        on_delete=models.CASCADE
    )
    tasker = models.ForeignKey(
        'users.User',
        verbose_name=_('Tasker'),
        related_name='customer_tasks',
        on_delete=models.CASCADE,
        **OPTIONAL
    )
    status = models.IntegerField(
        _('Status'),
        choices=STATUS_CHOICES,
        default=STATUS_PENDING
    )
    cost = models.DecimalField(_('Cost'), max_digits=15, decimal_places=2)
    address = models.CharField(_('Address'), max_length=255)
    start_date = models.DateTimeField(_('Start Date'))
    notes = models.TextField(_('Notes'), **OPTIONAL)

    class Meta:
        verbose_name = _('Tasks')
        verbose_name_plural = _('Tasks')

    def __str__(self):
        return str(self.id)

    def has_rated_by(self, user):
        return self.ratings.filter(task=self, sender=user).exists()


class Todo(TimeStampedModel):
    task = models.ForeignKey(
        'tasks.Task',
        verbose_name=_('Task'),
        related_name='todos',
        on_delete=models.CASCADE
    )
    description = models.TextField(_('Description'))

    class Meta:
        verbose_name = _('Todo')
        verbose_name_plural = _('Todos')

    def __str__(self):
        return str(self.task.id)


class TodoImage(models.Model):
    todo = models.ForeignKey(
        'tasks.Todo',
        verbose_name=_('Todo'),
        related_name='images',
        on_delete=models.CASCADE
    )
    image = models.ImageField(_('Image'), upload_to=get_images_upload_path)

    class Meta:
        verbose_name = _('Todo Image')
        verbose_name_plural = _('Todo Images')

    def __str__(self):
        return self.image.url


class Application(TimeStampedModel):
    task = models.ForeignKey(
        'tasks.Task',
        verbose_name=_('Task'),
        related_name='applications',
        on_delete=models.CASCADE
    )
    tasker = models.ForeignKey(
        'users.User',
        verbose_name=_('Tasker'),
        related_name='applications',
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = _('Application')
        verbose_name_plural = _('Applications')

    def __str__(self):
        return self.tasker.get_full_name()

apps/tasks/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.forms import formset_factory
from django.utils.translation import ugettext_lazy as _

from .models import (
    Application,
    Task,
    Todo,
    TodoImage,
)


User = get_user_model()


class TaskForm(forms.ModelForm):
    date = forms.DateField(
        label=_('Date'), widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(
        label=_('Time'), widget=forms.TimeInput(attrs={'type': 'time'}))

    class Meta:
        model = Task
        exclude = ('customer', 'tasker', 'status', 'start_date',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.todo_formset = TodoFormSet()
        self.initial = kwargs.get('initial')

    def clean(self):
        super().clean()
        self.todo_formset = TodoFormSet(self.data, self.files)

        if not self.todo_formset.is_valid():
            if self.todo_formset.non_form_errors():
                raise forms.ValidationError(
                    self.todo_formset.non_form_errors()[0])
            raise forms.ValidationError(
                _('Please check your todo task list errors below.'))

        return self.cleaned_data

    def save(self, *args, **kwargs):
        task = super().save(commit=False)
        date = self.cleaned_data.get('date')
        time = self.cleaned_data.get('time')

        try:
            task.customer
        except User.DoesNotExist:
            task.customer = self.initial.get('customer')

        task.start_date = datetime.combine(date, time)
        task.save()

        # save formset
        for form in self.todo_formset.forms:
            if form.is_valid() and form.cleaned_data:
                form.initial['task'] = task
                form.save()

        return task


class TodoForm(forms.ModelForm):
    images = forms.ImageField(
        label=_('Images'),
        required=False,
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

    class Meta:
        model = Todo
        exclude = ('task',)

    def save(self, *args, **kwargs):
        todo = super().save(commit=False)
        todo.task = self.initial.get('task')
        todo.save()

        try:
            images = self.files.getlist(f'{self.prefix}-images')
            for image in images:
                TodoImage.objects.create(
                    todo=todo,
                    image=image
                )
        except AttributeError:
            pass

        return todo


TodoFormSet = formset_factory(TodoForm, extra=1)


class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ('task',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial = kwargs.get('initial')

    def save(self, *args, **kwargs):
        application = super().save(commit=False)
        application.tasker = self.initial.get('user')
        application.save()

        return application


class TaskStatusUpdateForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('status',)


class AcceptTaskerForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('tasker',)

    def save(self, *args, **kwargs):
        task = super().save(commit=False)
        task.status = task.STATUS_ACCEPTED
        task.save()

        return task

apps/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import (
    Application,
    Category,
    Task,
)
from .forms import (
    AcceptTaskerForm,
    ApplicationForm,
    TaskForm,
    TaskStatusUpdateForm,
)
from apps.users.forms import RatingForm
from apps.users.models import Rating


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'tasks/task_list.html'

    def get_queryset(self):
        user = self.request.user

        queryset = user.tasks.all()
        if user.type == user.TYPE_TASKER:
            queryset = user.customer_tasks.all()

        return queryset.order_by('status')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rating_form'] = RatingForm(initial={'user': self.request.user})
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'


class AvailableTaskListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'tasks/available_task_list.html'

    def get_queryset(self):
        user = self.request.user
        category = self.request.GET.get('category', None)

        if user.type == user.TYPE_TASKER:
            applied_tasks = [application.task.id for application in user.applications.all()]
            queryset = Task.objects.filter(status=Task.STATUS_PENDING)
            if category:
                queryset = queryset.filter(category__pk=category)
            return queryset.exclude(id__in=applied_tasks)

        return HttpResponseNotFound('<h1>Page not found</h1>')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_manage.html'
    success_url = reverse_lazy('tasks:task-list')

    def get_initial(self):
        return {'customer': self.request.user}


class TaskApplyView(LoginRequiredMixin, CreateView):
    model = Application
    form_class = ApplicationForm
    template_name = 'tasks/task_apply.html'
    success_url = reverse_lazy('tasks:available-task-list')

    def get_initial(self):
        return {'user': self.request.user}


class TaskRatingView(LoginRequiredMixin, CreateView):
    model = Rating
    form_class = RatingForm
    template_name = 'tasks/rating.html'
    success_url = reverse_lazy('tasks:task-list')

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy('tasks:task-list'))

    def get_initial(self):
        task = Task.objects.get(id=self.kwargs.get('pk'))

        return {
            'user': self.request.user,
            'task': task,
        }


class TaskStatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    context_object_name = 'task'
    form_class = TaskStatusUpdateForm
    success_url = reverse_lazy('tasks:task-list')

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse_lazy('tasks:task-list'))


class AcceptTaskerView(LoginRequiredMixin, UpdateView):
    model = Task
    context_object_name = 'task'
    form_class = AcceptTaskerForm
    success_url = reverse_lazy('tasks:task-list')

    def get(self, request, *args, **kwargs):
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('tasks:task-detail', args=(self.kwargs.get('pk'),))

templates/tasks/available_task_list.html
{% extends 'base.html' %}

{% load humanize staticfiles %}

{% block header_css %}
<link href="{% static 'css/bootstrap-select.min.css' %}" rel="stylesheet">
{% endblock header_css %}

{% block content %}
<div class="col-md-12 mt-5">
    <div class="text-center mb-5">
        <select class="search-category" data-live-search="true" title="Filter by Category">
            {% for category in categories %}
                <option value="{{ category.id }}" {% if request.GET.category|add:"0" == category.id %}selected{% endif %}>{{ category.name }}</option>
            {% endfor %}
        </select>
    </div>

    {% for task in tasks %}
        <div class="card border-dark mb-5">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5">
                        <h4 class="card-title">{{ task.category }}</h4>
                        <h6 class="card-subtitle text-muted mb-2">${{ task.cost }}</h6>
                        <h6>{{ task.address }}</h6>
                        <p class="card-text">{{ task.notes }}</p>
                        <form class="row col-md-12" method="POST" action="{% url 'tasks:apply' task.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="task" id="id_task" value="{{ task.id }}">
                            <button type="submit" href="{% url 'tasks:task-detail' task.id %}" class="btn btn-primary mr-2">Apply</button>
                            <a href="{% url 'tasks:task-detail' task.id %}" class="btn btn-outline-primary">Details</a>
                        </form>
                    </div>
                    <div class="col-md-7">
                        <div class="card">
                            <ul class="list-group list-group-flush">
                                {% for item in task.todos.all %}
                                    <li class="list-group-item">
                                        <ul><li>{{ item.description }}</li></ul>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-white">Requested for <strong>{{ task.start_date.date }} @ {{ task.start_date.time }}</strong></small>
                <small class="text-white float-right">
                    Requested by
                    <a href="{% url 'users:profile' task.customer.pk %}" class="text-white"><strong>{{ task.customer.get_full_name }}</strong></a>
                </small>
            </div>
        </div>
    {% empty %}
        <div class="text-center">
            <h1>No available tasks yet.</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}

{% block footer_js %}
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/search_category.js' %}"></script>
{% endblock footer_js %}

templates/tasks/rating.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send message">
    </form>
{% endblock content %}

templates/tasks/task_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<div class="mt-5">
    <div class="row">
        <div class="col-md-5 text-center">
            <div class="card">
                <h5 class="card-header text-white
                    {% if task.status == task.STATUS_PENDING %}
                        bg-secondary
                    {% elif task.status == task.STATUS_ACCEPTED %}
                        bg-warning
                    {% elif task.status == task.STATUS_IN_PROGRESS %}
                        bg-primary
                    {% elif task.status == task.STATUS_DONE %}
                        bg-success
                    {% endif %}"
                >
                    {{ task.get_status_display|upper }}
                </h5>
                <div class="card-body">
                    <h4 class="card-title">{{ task.category }}</h4>
                    <h6 class="card-subtitle text-muted mb-2">${{ task.cost }}</h6>
                    <h6>{{ task.address }}</h6>
                    <p class="card-text">{{ task.notes }}</p>
                </div>
            </div>

            <div class="card mt-5">
                {% if task.status == task.STATUS_PENDING %}
                    <h4 class="card-header bg-dark text-white">Applicants</h4>
                    <div class="container">
                        <div class="applicants row mt-3">
                            {% for application in task.applications.all %}
                                <div class="col-md-4 text-center mb-3">
                                    <a href="#" data-toggle="modal" data-target="#modal-applicant-{{ application.tasker.id }}" class="link-unstyled">
                                        <img class="rounded-circle thumbnail mb-1" src="{% if application.tasker.image %}{{ application.tasker.image.url }}{% else %}{% static 'img/user.png' %}{% endif %}" alt="Profile Picture">
                                        <h5>{{ application.tasker.get_full_name }}</h5>
                                    </a>
                                </div>

                                <!-- Modal -->
                                <div class="modal fade" id="modal-applicant-{{ application.tasker.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="card">
                                                <img class="card-img-top" src="{% if application.tasker.image %}{{ application.tasker.image.url }}{% else %}{% static 'img/user.png' %}{% endif %}" alt="Profile Picture">
                                                <div class="card-body">
                                                    <div class="star-rating mt-1 mb-1">
                                                        {% for i in "12345"|center:"5" %}
                                                            {% if i|add:"0" <= application.tasker.average_rating %}
                                                                <i class="fas fa-star star"></i>
                                                            {% else %}
                                                                <i class="far fa-star star"></i>
                                                            {% endif %}
                                                        {% endfor %}
                                                    </div>
                                                    <h2 class="card-title">{{ application.tasker.get_full_name }}</h2>
                                                    <h6>{{ application.tasker.email }}</h6>
                                                    <h6>{{ application.tasker.contact }}</h6>

                                                    <form class="mt-3" method="POST" action="{% url 'tasks:accept-tasker' task.id %}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="tasker" id="id_tasker" value="{{ application.tasker.id }}">

                                                        <a href="{% url 'users:profile' application.tasker.id %}" class="btn btn-lg btn-primary">Profile</a>
                                                        <button type="submit" class="btn btn-lg btn-danger">Accept</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    <h3 class="card-header bg-dark text-white">Tasker</h3>
                    <div class="text-center mb-3 mt-3">
                        <a href="#" data-toggle="modal" data-target="#modal-tasker" class="link-unstyled">
                            <img class="rounded-circle thumbnail mb-1" src="{% if task.tasker.image %}{{ task.tasker.image.url }}{% else %}{% static 'img/user.png' %}{% endif %}" alt="Profile Picture">
                            <h5>{{ task.tasker.get_full_name }}</h5>
                        </a>

                        <!-- Modal -->
                        <div class="modal fade" id="modal-tasker" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="card">
                                            <img class="card-img-top" src="{% if task.tasker.image %}{{ task.tasker.image.url }}{% else %}{% static 'img/user.png' %}{% endif %}" alt="Profile Picture">
                                            <div class="card-body">
                                                <div class="star-rating mt-1 mb-1">
                                                    {% for i in "12345"|center:"5" %}
                                                        {% if i|add:"0" <= task.tasker.average_rating %}
                                                            <i class="fas fa-star star"></i>
                                                        {% else %}
                                                            <i class="far fa-star star"></i>
                                                        {% endif %}
                                                    {% endfor %}
                                                </div>
                                                <h2 class="card-title">{{ task.tasker.get_full_name }}</h2>
                                                <h6>{{ task.tasker.email }}</h6>
                                                <h6>{{ task.tasker.contact }}</h6>

                                                <div class="buttons mt-3">
                                                    <a href="{% url 'users:profile' task.tasker.id %}" class="btn btn-lg btn-primary data-dismiss="modal">Profile</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% for item in task.todos.all %}
                        <li class="list-group-item">
                            <i class="fas fa-check"></i> {{ item.description }}
                            <div class="row">
                                {% for image in item.images.all %}
                                    <div class="m-3">
                                        <img src="{{ image.image.url }}" alt="todo Image" class="todo-image">
                                    </div>
                                {% endfor %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/tasks/task_list.html
{% extends 'base.html' %}

{% load humanize staticfiles task_tags bootstrap4 %}

{% block header_css %}
<link rel="stylesheet" href="{% static 'css/rating.css' %}">
{% endblock header_css %}

{% block content %}
<div class="col-md-12 mt-5">
    {% for task in tasks %}
        <div class="card border-dark mb-5">
            <h6 class="card-header text-white
                {% if task.status == task.STATUS_PENDING %}
                    bg-secondary
                {% elif task.status == task.STATUS_ACCEPTED %}
                    bg-warning
                {% elif task.status == task.STATUS_IN_PROGRESS %}
                    bg-primary
                {% elif task.status == task.STATUS_DONE %}
                    bg-success
                {% endif %}"
            >
                {{ task.get_status_display|upper }}
            </h6>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5">
                        <h4 class="card-title">{{ task.category }}</h4>
                        <h6 class="card-subtitle text-muted mb-2">${{ task.cost }}</h6>
                        <h6>{{ task.address }}</h6>
                        <p class="card-text">{{ task.notes }}</p>
                        <form class="row col-md-12" method="POST" action="{% url 'tasks:status-update' task.id %}">
                            {% csrf_token %}
                            {% if user.type == user.TYPE_TASKER %}
                                {% if task.status == task.STATUS_ACCEPTED or task.status == task.STATUS_IN_PROGRESS  %}
                                    <input type="hidden" value="{{ task.status|add:'1' }}" name="status">
                                        {% if task.status == task.STATUS_ACCEPTED %}
                                            <button type="submit" href="{% url 'tasks:task-detail' task.id %}" class="btn btn-primary mr-2">
                                                Start Task
                                            </button>
                                        {% elif task.status == task.STATUS_IN_PROGRESS %}
                                            <button type="submit" href="{% url 'tasks:task-detail' task.id %}" class="btn btn-success mr-2">
                                                Finish Task
                                            </button>
                                        {% endif %}
                                {% endif %}

                                {% if task.status == task.STATUS_DONE and not user|has_rated:task %}
                                    <a class="btn btn-warning mr-2" data-toggle="modal" data-target="#rate-{{ task.id }}">Rate</a>
                                {% endif %}
                            {% endif %}
                            <a href="{% url 'tasks:task-detail' task.id %}" class="btn btn-outline-dark">Details</a>
                        </form>

                        <!-- Modal -->
                        <div class="modal fade" id="rate-{{ task.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        <form method="POST" action="{% url 'tasks:rate' task.id %}">
                                            {% csrf_token %}
                                            {% bootstrap_form_errors rating_form %}

                                            {% bootstrap_field rating_form.rate show_label=False %}
                                            {% bootstrap_field rating_form.remarks %}

                                            <div class="text-center mt-4">
                                                <button type="submit" class="btn btn-lg btn-warning">Rate</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="card">
                            <ul class="list-group list-group-flush">
                                {% for item in task.todos.all %}
                                    <li class="list-group-item">
                                        <i class="fas fa-check"></i> {{ item.description }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer bg-dark">
                <small class="text-white">Requested for <strong>{{ task.start_date.date }} @ {{ task.start_date.time }}</strong></small>
                <small class="text-white float-right">
                    {% if user.type == user.TYPE_TASKER %}
                        Requested by
                        <a href="{% url 'users:profile' task.customer.pk %}" class="text-white"><strong>{{ task.customer.get_full_name }}</strong></a>
                    {% else %}
                        {% if task.tasker %}
                            Tasked by
                            <a href="{% url 'users:profile' task.tasker.pk %}" class="text-white"><strong>{{ task.tasker.get_full_name }}</strong></a>
                        {% else %}
                            Applicants: <strong>{{ task.applications.count }}</strong>
                        {% endif %}
                    {% endif %}
                </small>
            </div>
        </div>
    {% empty %}
        <div class="text-center">
            <h1>You have no tasks yet.</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}


{% block footer_js %}
<script src="{% static 'js/rating.js' %}"></script>
<script>
    $(document).ready(function(){
        $('.rating').rating();
    });
</script>
{% endblock footer_js %}

templates/tasks/tasker_dashboard.html
{% extends 'base.html' %}


{% block content %}
    {{ my_tasks }}
{% endblock content %}